name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
  - type: checkboxes
  attributes:
    label: Reproducibility
    description: Please try to reproduce the issue with as few other mods as possible. Then check one of the following checkboxes according to your results.
    options:
    - label: I reproduced this issue with as few other mods as possible installed.
      required: false
    - label: I am unable to reproduce this issue consistently.
      required: false  
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Explain clearly what happened.
      placeholder: Tell us what happened!
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Explain the behavior you expect.
      placeholder: Tell us what you want to happen!
    validations:
      required: false
  - type: textarea
    id: to-reproduce
    attributes:
      label: To reproduce
      description: Explain how to reproduce what happened.
      placeholder: Tell us how to reproduce the issue!
    validations:
      required: false
  - type: input
    id: logs-crash-reports
    attributes:
      label: Logs and/or crash reports
      placeholder: https://mclo.gs/
    validations:
      required: true
  - type: input
    id: mod-version
    attributes:
      label: Mod version
      placeholder: eg. 0.1-Dev-12
    validations:
      required: true
  - type: dropdown
    id: gpu-vendor
    attributes:
      label: GPU Brand
      options:
        - AMD
        - NVIDIA
        - Intel
    validations:
      required: true    
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/Cubed-Development/Modern-Warfare-Cubed/blob/master/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
