name: Qodana

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    
    steps:
      - name: Code Checkout
        uses: actions/checkout@v3.5.3

          
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.1.5
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
          
      - name: Qodana GitHub Report
        uses: github/codeql-action/upload-sarif@v2.20.3
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
