name: Initialize Docusaurus
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Initialize Docusaurus
        run: |
          npx @docusaurus/init@latest init documentation classic
      - name: Push to repository
        run: |
          git config --global user.email "desoroxxx@gmail.com"
          git config --global user.name "Desoroxxx"
          git add -A
          git commit -m "Initialize Docusaurus"
          git push
